version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis-server